print('== TABUADA ==')
num = int(input('digite o número desejado'))
print(f'{num}x1 = {num*1}')
print(f'{num}x2 = {num*2}')
print(f'{num}x3 = {num*3}')
print(f'{num}x4 = {num*4}')
print(f'{num}x5 = {num*5}')
print(f'{num}x6 = {num*6}')
print(f'{num}x7 = {num*7}')
print(f'{num}x8 = {num*8}')
print(f'{num}x9 = {num*9}')
print(f'{num}x10 = {num*10}')
